import type { Employee, Branch } from '@/types';

// Branch data based on spreadsheet
export const BRANCHES: Branch[] = [
  {
    id: 'yunusabad',
    name: 'C-Space Yunusabad',
    address: 'Yunusabad, Tashkent',
    latitude: 41.3385,
    longitude: 69.2890,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'labzak',
    name: 'C-Space Labzak',
    address: 'Labzak, Tashkent',
    latitude: 41.3117,
    longitude: 69.2787,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'elbek',
    name: 'C-Space Elbek',
    address: 'Elbek, Tashkent',
    latitude: 41.3050,
    longitude: 69.2700,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'chust',
    name: 'C-Space Chust',
    address: 'Chust, Tashkent',
    latitude: 41.2950,
    longitude: 69.2800,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'maksim-gorkiy',
    name: 'C-Space Maksim Gorkiy',
    address: 'Maksim Gorkiy, Tashkent',
    latitude: 41.3200,
    longitude: 69.2500,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'aero',
    name: 'C-Space Aero',
    address: 'Aero, Tashkent',
    latitude: 41.2700,
    longitude: 69.2800,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'orient',
    name: 'C-Space Orient',
    address: 'Beruniy, Tashkent',
    latitude: 41.3000,
    longitude: 69.2900,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'muqimiy',
    name: 'C-Space Muqimiy',
    address: 'Muqimiy, Tashkent',
    latitude: 41.3100,
    longitude: 69.2600,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'yunus-obod',
    name: 'C-Space Yunus-Obod',
    address: 'Yunus-Obod, Tashkent',
    latitude: 41.3400,
    longitude: 69.3000,
    geofenceRadius: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Employee data based on the spreadsheet "Hodimlar Ro'yxati"
export const EMPLOYEES: Employee[] = [
  // === C-SPACE YUNUSABAD ===
  {
    id: '1',
    employeeId: 'EMP001',
    fullName: 'Nodir Mahmudov',
    position: 'BM',
    level: 'middle',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad',
    employmentType: 'full_time',
    baseSalary: 5000000,
    advanceBank: 2500000,
    salaryBank: 2500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    employeeId: 'EMP002',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad',
    employmentType: 'part_time',
    baseSalary: 1800000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    employeeId: 'EMP003',
    fullName: 'Nigina Umaraliyeva',
    position: 'Legal Manager',
    level: 'middle',
    branchId: 'yunusabad',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 9000000,
    salaryBank: 9000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    employeeId: 'EMP004',
    fullName: 'Yusufjon Sayfullayev',
    position: 'NS',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'Muqimiy',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 900000,
    salaryBank: 2430000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    employeeId: 'EMP005',
    fullName: 'Ruxshona Nabijonova',
    position: 'QA',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'All',
    employmentType: 'part_time',
    baseSalary: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    employeeId: 'EMP006',
    fullName: 'Shahzod Xabibjonov',
    position: 'NS',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 1700000,
    salaryBank: 1800000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    employeeId: 'EMP007',
    fullName: 'Rahmatulloh Yusupov',
    position: 'Facility Manager',
    level: 'middle',
    branchId: 'yunusabad',
    branchLocation: 'Yandex',
    employmentType: 'full_time',
    baseSalary: 7500000,
    salaryBank: 7500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    employeeId: 'EMP008',
    fullName: 'Jamshid Farhodov',
    position: 'NS',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    employeeId: 'EMP009',
    fullName: 'Xushbaxt Abdusalomov',
    position: 'NS',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceCash: 1500000,
    salaryCash: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    employeeId: 'EMP010',
    fullName: 'Paxlavon Mahmud Begijonov',
    position: 'NS',
    level: 'middle',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad, Aero',
    employmentType: 'full_time',
    baseSalary: 4000000,
    salaryBank: 4000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    employeeId: 'EMP011',
    fullName: 'Axror Umarov',
    position: 'CM',
    level: 'junior',
    branchId: 'yunusabad',
    branchLocation: 'Yunusabad',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 1750000,
    salaryBank: 1750000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    employeeId: 'EMP012',
    fullName: 'Sayyora Sharipova',
    position: 'Accounting Manager',
    level: 'middle',
    branchId: 'yunusabad',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 7000000,
    salaryBank: 7000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === CS LABZAK ===
  {
    id: '13',
    employeeId: 'EMP013',
    fullName: 'Sulhiya Aminova',
    position: 'QA',
    level: 'middle',
    branchId: 'labzak',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 6000000,
    advanceBank: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '14',
    employeeId: 'EMP014',
    fullName: 'Abror Umarov',
    position: 'BM',
    level: 'middle',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 5500000,
    advanceBank: 1500000,
    salaryBank: 3500000,
    salaryCash: 500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '15',
    employeeId: 'EMP015',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'part_time',
    baseSalary: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '16',
    employeeId: 'EMP016',
    fullName: 'Zuxriddin Abduraxmonov',
    position: 'GM',
    level: 'executive',
    branchId: 'labzak',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '17',
    employeeId: 'EMP017',
    fullName: 'Xusravbek Olimjonov',
    position: 'NS',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '18',
    employeeId: 'EMP018',
    fullName: 'Bekzod Tursunaliev',
    position: 'NS',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '19',
    employeeId: 'EMP019',
    fullName: 'Fozilbek Akmalov',
    position: 'CM',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Beruniy',
    employmentType: 'part_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '20',
    employeeId: 'EMP020',
    fullName: 'Lobarxon Abdurasulova',
    position: 'AXO',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 1750000,
    salaryBank: 1750000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '21',
    employeeId: 'EMP021',
    fullName: 'Akmal Ibodullayev',
    position: 'CM',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 3000000,
    salaryCash: 1000000,
    notes: '10-oktabrdan sinovda',
    status: 'probation',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: '22',
    employeeId: 'EMP022',
    fullName: 'Guljamoл Kenjabayeva',
    position: 'AXO',
    level: 'junior',
    branchId: 'labzak',
    branchLocation: 'Labzak',
    employmentType: 'full_time',
    baseSalary: 4500000,
    advanceBank: 2250000,
    salaryBank: 2250000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === CS-ELBEK ===
  {
    id: '23',
    employeeId: 'EMP023',
    fullName: 'Nodirbek Yusupov',
    position: 'Maintenance',
    level: 'middle',
    branchId: 'elbek',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 5000000,
    salaryBank: 5000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '24',
    employeeId: 'EMP024',
    fullName: 'Ibrohim Abduqodirov',
    position: 'BM',
    level: 'middle',
    branchId: 'elbek',
    branchLocation: 'Elbek',
    employmentType: 'full_time',
    baseSalary: 5000000,
    advanceBank: 5000000,
    notes: 'Will be fired from Nov.',
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '25',
    employeeId: 'EMP025',
    fullName: 'Munira Bababekova',
    position: 'AXO',
    level: 'senior',
    branchId: 'elbek',
    branchLocation: 'Elbek',
    employmentType: 'full_time',
    baseSalary: 6000000,
    salaryBank: 6000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '26',
    employeeId: 'EMP026',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'elbek',
    branchLocation: 'Elbek',
    employmentType: 'part_time',
    baseSalary: 1400000,
    salaryBank: 1400000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '27',
    employeeId: 'EMP027',
    fullName: 'Ibrohim Oripov',
    position: 'CM',
    level: 'junior',
    branchId: 'elbek',
    branchLocation: 'Elbek',
    employmentType: 'part_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    notes: '1-avgustdan olingan',
    status: 'active',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: '28',
    employeeId: 'EMP028',
    fullName: 'Rakhmatov Fozilkhon',
    position: 'CM',
    level: 'junior',
    branchId: 'elbek',
    branchLocation: 'Beruniy',
    employmentType: 'part_time',
    baseSalary: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '29',
    employeeId: 'EMP029',
    fullName: 'Salim Avazov',
    position: 'NS',
    level: 'junior',
    branchId: 'elbek',
    branchLocation: 'Elbek',
    employmentType: 'full_time',
    baseSalary: 2000000,
    salaryBank: 2000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === C-SPACE CHUST ===
  {
    id: '30',
    employeeId: 'EMP030',
    fullName: 'Durbek Shaymardanov',
    position: 'Construction Manager',
    level: 'middle',
    branchId: 'chust',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 15000000,
    salaryBank: 15000000,
    notes: "E'zoza Meliboyeva",
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '31',
    employeeId: 'EMP031',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'chust',
    branchLocation: 'Chust',
    employmentType: 'part_time',
    baseSalary: 1400000,
    salaryBank: 1400000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '32',
    employeeId: 'EMP032',
    fullName: 'Oyxol Egamberdiyeva',
    position: 'AXO',
    level: 'middle',
    branchId: 'chust',
    branchLocation: 'Aero',
    employmentType: 'full_time',
    baseSalary: 4000000,
    advanceBank: 1000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '33',
    employeeId: 'EMP033',
    fullName: 'Gavhar Abdigayeva',
    position: 'AXO',
    level: 'middle',
    branchId: 'chust',
    branchLocation: 'Yandex',
    employmentType: 'full_time',
    baseSalary: 4500000,
    salaryBank: 4500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '34',
    employeeId: 'EMP034',
    fullName: 'Saodat Rahimova',
    position: 'AXO',
    level: 'middle',
    branchId: 'chust',
    branchLocation: 'Yandex',
    employmentType: 'full_time',
    baseSalary: 4500000,
    salaryBank: 4500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '35',
    employeeId: 'EMP035',
    fullName: 'Xurshida Muxamedjanova',
    position: 'AXO',
    level: 'middle',
    branchId: 'chust',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 1800000,
    salaryBank: 1800000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '36',
    employeeId: 'EMP036',
    fullName: 'Samad Gaipov',
    position: 'Sales Intern',
    level: 'junior',
    branchId: 'chust',
    branchLocation: 'All',
    employmentType: 'part_time',
    baseSalary: 4500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === C-SPACE MAKSIM GORKIY ===
  {
    id: '37',
    employeeId: 'EMP037',
    fullName: "Nabijon Turg'unov",
    position: 'CEO Assistant',
    level: 'middle',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 10000000,
    salaryBank: 10000000,
    notes: 'Aziz aka',
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '38',
    employeeId: 'EMP038',
    fullName: 'Javlon Toshpulatov',
    position: 'BM',
    level: 'middle',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 5000000,
    advanceBank: 2000000,
    salaryBank: 3000000,
    notes: 'Will be fired from Nov.',
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '39',
    employeeId: 'EMP039',
    fullName: 'Mohigul Yuldoshova',
    position: 'AXO',
    level: 'middle',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 1000000,
    salaryBank: 2500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '40',
    employeeId: 'EMP040',
    fullName: 'Ubaydullo Pulat',
    position: 'Business Developer',
    level: 'executive',
    branchId: 'maksim-gorkiy',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 19000000,
    salaryBank: 19000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '41',
    employeeId: 'EMP041',
    fullName: 'Jamshid Ibragimov',
    position: 'NS',
    level: 'junior',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '42',
    employeeId: 'EMP042',
    fullName: 'Suxrob Usmonov',
    position: 'NS',
    level: 'junior',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceBank: 1000000,
    salaryBank: 2000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '43',
    employeeId: 'EMP043',
    fullName: 'Usarova Ulbosin',
    position: 'AXO',
    level: 'middle',
    branchId: 'maksim-gorkiy',
    branchLocation: 'Chust',
    employmentType: 'full_time',
    baseSalary: 3500000,
    advanceBank: 1000000,
    salaryBank: 2500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === CS AERO ===
  {
    id: '44',
    employeeId: 'EMP044',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'aero',
    branchLocation: 'Aero',
    employmentType: 'part_time',
    baseSalary: 1000000,
    salaryBank: 1000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '45',
    employeeId: 'EMP045',
    fullName: 'Nodirbek Yusupov',
    position: 'Maintenance',
    level: 'middle',
    branchId: 'aero',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 3000000,
    advanceBank: 1500000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '46',
    employeeId: 'EMP046',
    fullName: 'Abubakr Sodiqov',
    position: 'NS',
    level: 'junior',
    branchId: 'aero',
    branchLocation: 'Aero',
    employmentType: 'full_time',
    baseSalary: 2500000,
    advanceBank: 1000000,
    salaryBank: 1500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '47',
    employeeId: 'EMP047',
    fullName: 'Humoyun Odilov',
    position: 'CM',
    level: 'junior',
    branchId: 'aero',
    branchLocation: 'Aero',
    employmentType: 'full_time',
    baseSalary: 4000000,
    advanceBank: 1000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === C-SPACE ORIENT (BERUNIY) ===
  {
    id: '48',
    employeeId: 'EMP048',
    fullName: 'Nargiza Rahimova',
    position: 'AXO',
    level: 'middle',
    branchId: 'orient',
    branchLocation: 'Beruniy',
    employmentType: 'full_time',
    baseSalary: 4500000,
    advanceBank: 1500000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '49',
    employeeId: 'EMP049',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'orient',
    branchLocation: 'Beruniy',
    employmentType: 'part_time',
    baseSalary: 1000000,
    salaryBank: 1000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '50',
    employeeId: 'EMP050',
    fullName: 'Mirabrorov Mirasror',
    position: 'CM',
    level: 'junior',
    branchId: 'orient',
    branchLocation: 'Beruniy',
    employmentType: 'full_time',
    baseSalary: 3000000,
    salaryBank: 3000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '51',
    employeeId: 'EMP051',
    fullName: 'Gularoxon Nurobiddinova',
    position: 'CM',
    level: 'junior',
    branchId: 'orient',
    branchLocation: 'Beruniy',
    employmentType: 'part_time',
    baseSalary: 2500000,
    advanceBank: 1000000,
    salaryBank: 1500000,
    notes: 'Will be fired from Nov.',
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  // === CSPACE MUQIMIY ===
  {
    id: '52',
    employeeId: 'EMP052',
    fullName: 'Asomitdinov Muhammadamin',
    position: 'Yuridik Direktor',
    level: 'executive',
    branchId: 'muqimiy',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 0,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '53',
    employeeId: 'EMP053',
    fullName: 'Said',
    position: 'Florist',
    level: 'senior',
    branchId: 'muqimiy',
    branchLocation: 'Muqimiy',
    employmentType: 'part_time',
    baseSalary: 700000,
    salaryBank: 700000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '54',
    employeeId: 'EMP054',
    fullName: 'Azizbek Samiyev',
    position: 'CM',
    level: 'junior',
    branchId: 'muqimiy',
    branchLocation: 'Muqimiy',
    employmentType: 'full_time',
    baseSalary: 4000000,
    advanceBank: 1500000,
    salaryBank: 3000000,
    notes: '1-sentabrdan',
    status: 'active',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
  },
  // === CS YUNUS-OBOD ===
  {
    id: '55',
    employeeId: 'EMP055',
    fullName: 'Yusupov Rahmatulloh',
    position: 'Facility Manager',
    level: 'middle',
    branchId: 'yunus-obod',
    branchLocation: 'Yandex',
    employmentType: 'full_time',
    baseSalary: 7500000,
    salaryBank: 7500000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '56',
    employeeId: 'EMP056',
    fullName: 'Maxmudjon Bustonov',
    position: 'Operations Specialist',
    level: 'middle',
    branchId: 'yunus-obod',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 8000000,
    salaryBank: 6000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '57',
    employeeId: 'EMP057',
    fullName: 'Raimbеkov Мирвохид (Sales)',
    position: 'Sales Manager',
    level: 'middle',
    branchId: 'yunus-obod',
    branchLocation: 'All',
    employmentType: 'full_time',
    baseSalary: 8000000,
    advanceBank: 4000000,
    salaryBank: 4000000,
    status: 'active',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Helper functions
export function getEmployeesByBranch(branchId: string): Employee[] {
  return EMPLOYEES.filter(emp => emp.branchId === branchId && emp.status !== 'terminated');
}

export function getBranchById(branchId: string): Branch | undefined {
  return BRANCHES.find(branch => branch.id === branchId);
}

export function getActiveEmployeesCount(): number {
  return EMPLOYEES.filter(emp => emp.status === 'active' || emp.status === 'probation').length;
}

export function getTotalSalaryBudget(): number {
  return EMPLOYEES
    .filter(emp => emp.status === 'active' || emp.status === 'probation')
    .reduce((sum, emp) => sum + emp.baseSalary, 0);
}

export function getEmployeesByLevel(level: string): Employee[] {
  return EMPLOYEES.filter(emp => emp.level === level && emp.status !== 'terminated');
}

export function getEmployeesByPosition(position: string): Employee[] {
  return EMPLOYEES.filter(emp => emp.position === position && emp.status !== 'terminated');
}
