-- Migration: Create Clients Table and Import Data
-- Date: 2026-01-31
-- Description: Creates clients database for customer management

-- ============================================
-- 1. CREATE CLIENTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Basic Info
  name VARCHAR(255) NOT NULL,              -- Display name
  name_normalized VARCHAR(255),            -- Uppercase for matching
  client_type VARCHAR(20) NOT NULL         -- 'company' | 'individual'
    CHECK (client_type IN ('company', 'individual')),
  
  -- Company Details (for companies)
  legal_name VARCHAR(255),                 -- Full legal name (OOO «...»)
  industry VARCHAR(100),                   -- IT, Finance, Healthcare, etc.
  
  -- Contact Info
  phone VARCHAR(50),
  email VARCHAR(255),
  
  -- Metadata
  notes TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  branch_id VARCHAR REFERENCES branches(id),  -- Primary branch association
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Constraints
  UNIQUE(name_normalized, branch_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_clients_name ON clients(name);
CREATE INDEX IF NOT EXISTS idx_clients_name_normalized ON clients(name_normalized);
CREATE INDEX IF NOT EXISTS idx_clients_type ON clients(client_type);
CREATE INDEX IF NOT EXISTS idx_clients_branch ON clients(branch_id);
CREATE INDEX IF NOT EXISTS idx_clients_active ON clients(is_active);

-- ============================================
-- 2. ADD CLIENT_ID TO TRANSACTIONS TABLE
-- ============================================
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES clients(id);

CREATE INDEX IF NOT EXISTS idx_transactions_client ON transactions(client_id);

-- ============================================
-- 3. TRIGGER FOR UPDATED_AT
-- ============================================
CREATE TRIGGER update_clients_timestamp
  BEFORE UPDATE ON clients
  FOR EACH ROW
  EXECUTE FUNCTION trigger_update_reception_timestamp();

-- ============================================
-- 4. ROW LEVEL SECURITY
-- ============================================
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON clients
  FOR ALL USING (true);

GRANT ALL ON clients TO authenticated;

-- ============================================
-- 5. INSERT CLIENT DATA (Labzak Branch)
-- ============================================
INSERT INTO clients (name, name_normalized, client_type, industry, branch_id) VALUES
  ('Harlapanov', 'HARLAPANOV', 'individual', NULL, 'labzak'),
  ('Normatov', 'NORMATOV', 'individual', NULL, 'labzak'),
  ('MANPOWER KAZ', 'MANPOWER KAZ', 'company', NULL, 'labzak'),
  ('JICA', 'JICA', 'company', NULL, 'labzak'),
  ('Tradebuild Ta''minot', 'TRADEBUILD TA''MINOT', 'company', NULL, 'labzak'),
  ('INVITRIS', 'INVITRIS', 'company', 'Healthcare', 'labzak'),
  ('Masharipov', 'MASHARIPOV', 'individual', NULL, 'labzak'),
  ('UNITED KINGS', 'UNITED KINGS', 'company', NULL, 'labzak'),
  ('IMAN', 'IMAN', 'company', NULL, 'labzak'),
  ('APPLIED LABS', 'APPLIED LABS', 'company', NULL, 'labzak'),
  ('NEO STYLE', 'NEO STYLE', 'company', NULL, 'labzak'),
  ('BCI', 'BCI', 'company', NULL, 'labzak'),
  ('GRAND AERO GROUP', 'GRAND AERO GROUP', 'company', NULL, 'labzak'),
  ('MATTE', 'MATTE', 'company', NULL, 'labzak'),
  ('Abidov Timur', 'ABIDOV TIMUR', 'individual', NULL, 'labzak'),
  ('Sobirjonov Abdukodir', 'SOBIRJONOV ABDUKODIR', 'individual', NULL, 'labzak'),
  ('Ergashev Ibrohim', 'ERGASHEV IBROHIM', 'individual', NULL, 'labzak'),
  ('Adizov Sanjar', 'ADIZOV SANJAR', 'individual', NULL, 'labzak'),
  ('Jabbarov Askhat', 'JABBAROV ASKHAT', 'individual', NULL, 'labzak'),
  ('Pak Eleonora', 'PAK ELEONORA', 'individual', NULL, 'labzak'),
  ('Shermukhammedov Sherzod', 'SHERMUKHAMMEDOV SHERZOD', 'individual', NULL, 'labzak'),
  ('SVB ADVISORY', 'SVB ADVISORY', 'company', NULL, 'labzak'),
  ('Islomov Kamoliddin', 'ISLOMOV KAMOLIDDIN', 'individual', NULL, 'labzak'),
  ('Mukhiddinov Khusniddin', 'MUKHIDDINOV KHUSNIDDIN', 'individual', NULL, 'labzak'),
  ('All', 'ALL', 'individual', NULL, 'labzak'),
  ('Farmanova', 'FARMANOVA', 'individual', NULL, 'labzak'),
  ('CHEMONICS', 'CHEMONICS', 'company', NULL, 'labzak'),
  ('Yuldashev', 'YULDASHEV', 'individual', NULL, 'labzak'),
  ('Sobirjonov', 'SOBIRJONOV', 'individual', NULL, 'labzak'),
  ('Sagdullaev Akmal', 'SAGDULLAEV AKMAL', 'individual', NULL, 'labzak'),
  ('OKSTORE', 'OKSTORE', 'company', NULL, 'labzak'),
  ('Irina Hvan', 'IRINA HVAN', 'individual', NULL, 'labzak'),
  ('Printing', 'PRINTING', 'individual', NULL, 'labzak'),
  ('Office', 'OFFICE', 'individual', NULL, 'labzak'),
  ('Mohseni', 'MOHSENI', 'company', NULL, 'labzak'),
  ('Haydarov Abdulaziz', 'HAYDAROV ABDULAZIZ', 'individual', NULL, 'labzak'),
  ('Abdullaev Bobur', 'ABDULLAEV BOBUR', 'individual', NULL, 'labzak'),
  ('Zokirbek Khojiakbarbekov', 'ZOKIRBEK KHOJIAKBARBEKOV', 'individual', NULL, 'labzak'),
  ('Aleksandr', 'ALEKSANDR', 'individual', NULL, 'labzak'),
  ('Jonuzokov Doston', 'JONUZOKOV DOSTON', 'individual', NULL, 'labzak'),
  ('Mitskih', 'MITSKIH', 'individual', NULL, 'labzak'),
  ('Tuhtabaev Saidamir', 'TUHTABAEV SAIDAMIR', 'individual', NULL, 'labzak'),
  ('Tilyaev Alisher', 'TILYAEV ALISHER', 'individual', NULL, 'labzak'),
  ('Eshchanov Odilbek', 'ESHCHANOV ODILBEK', 'individual', NULL, 'labzak'),
  ('ZONE AGENCY', 'ZONE AGENCY', 'company', NULL, 'labzak'),
  ('Rustamov Khurshid', 'RUSTAMOV KHURSHID', 'individual', NULL, 'labzak'),
  ('Karimov Salohiddin', 'KARIMOV SALOHIDDIN', 'individual', NULL, 'labzak'),
  ('Bahriddinova Osiyo', 'BAHRIDDINOVA OSIYO', 'individual', NULL, 'labzak'),
  ('Muraev Tahir', 'MURAEV TAHIR', 'individual', NULL, 'labzak'),
  ('Viktor Bilkov', 'VIKTOR BILKOV', 'individual', NULL, 'labzak'),
  ('Eleonora Pak', 'ELEONORA PAK', 'individual', NULL, 'labzak'),
  ('PERSPECTIVE CONSULTING', 'PERSPECTIVE CONSULTING', 'company', NULL, 'labzak'),
  ('Isomiddinov Sirojiddin', 'ISOMIDDINOV SIROJIDDIN', 'individual', NULL, 'labzak'),
  ('Abdukodirov Bekzod', 'ABDUKODIROV BEKZOD', 'individual', NULL, 'labzak'),
  ('Asakarov Muhammadjon', 'ASAKAROV MUHAMMADJON', 'individual', NULL, 'labzak'),
  ('Tufekci Ali', 'TUFEKCI ALI', 'individual', NULL, 'labzak'),
  ('Viktoriya Pak', 'VIKTORIYA PAK', 'individual', NULL, 'labzak'),
  ('Abdukarimova Sanobar', 'ABDUKARIMOVA SANOBAR', 'individual', NULL, 'labzak'),
  ('KINOTEATR', 'KINOTEATR', 'company', NULL, 'labzak'),
  ('JOY DESIGN', 'JOY DESIGN', 'company', NULL, 'labzak'),
  ('CHRONUS', 'CHRONUS', 'company', NULL, 'labzak'),
  ('EL VAC SYSTEM', 'EL VAC SYSTEM', 'company', NULL, 'labzak'),
  ('Odiljon Eshchanov', 'ODILJON ESHCHANOV', 'individual', NULL, 'labzak'),
  ('Alimatov Oybek', 'ALIMATOV OYBEK', 'individual', NULL, 'labzak'),
  ('Yuldashev Ruslan', 'YULDASHEV RUSLAN', 'individual', NULL, 'labzak'),
  ('Abdurakhmonov Dilshod', 'ABDURAKHMONOV DILSHOD', 'individual', NULL, 'labzak'),
  ('OASIS AUDIT', 'OASIS AUDIT', 'company', NULL, 'labzak'),
  ('Azizbek Mavlyanov', 'AZIZBEK MAVLYANOV', 'individual', NULL, 'labzak'),
  ('PROFI STAFF', 'PROFI STAFF', 'company', 'Education', 'labzak'),
  ('Farruh Turgunov', 'FARRUH TURGUNOV', 'individual', NULL, 'labzak'),
  ('PARQOUR', 'PARQOUR', 'company', NULL, 'labzak'),
  ('POWER ASIA ENERGY', 'POWER ASIA ENERGY', 'company', NULL, 'labzak'),
  ('Sanjar Mirahmedov', 'SANJAR MIRAHMEDOV', 'individual', NULL, 'labzak'),
  ('Otabek Nurmatov', 'OTABEK NURMATOV', 'individual', NULL, 'labzak'),
  ('Sadati Hadar', 'SADATI HADAR', 'individual', NULL, 'labzak'),
  ('Obidov Bekzod', 'OBIDOV BEKZOD', 'individual', NULL, 'labzak'),
  ('Sanjar Adizov', 'SANJAR ADIZOV', 'individual', 'IT', 'labzak'),
  ('Islom Jangboev', 'ISLOM JANGBOEV', 'individual', NULL, 'labzak'),
  ('Mitskih + Aziz', 'MITSKIH + AZIZ', 'individual', NULL, 'labzak'),
  ('EXPORTGROUP', 'EXPORTGROUP', 'individual', NULL, 'labzak'),
  ('Abduraxmonov Dilshod', 'ABDURAXMONOV DILSHOD', 'individual', NULL, 'labzak'),
  ('Bilko', 'BILKO', 'company', NULL, 'labzak'),
  ('BUYSELL', 'BUYSELL', 'company', NULL, 'labzak'),
  ('Erik', 'ERIK', 'individual', NULL, 'labzak'),
  ('Mir Islom Mirakbarov', 'MIR ISLOM MIRAKBAROV', 'individual', NULL, 'labzak'),
  ('AMINALAB', 'AMINALAB', 'company', NULL, 'labzak'),
  ('WATERFALLS AND WATER FEATURES', 'WATERFALLS AND WATER FEATURES', 'company', NULL, 'labzak'),
  ('PROFIT SERVICE PREMIUM', 'PROFIT SERVICE PREMIUM', 'company', 'Finance', 'labzak'),
  ('Sherzod Karimov (BuySell)', 'SHERZOD KARIMOV (BUYSELL)', 'individual', NULL, 'labzak'),
  ('Aleksey Kutepov', 'ALEKSEY KUTEPOV', 'individual', NULL, 'labzak'),
  ('Zokirbekov Khojiakbarbek', 'ZOKIRBEKOV KHOJIAKBARBEK', 'individual', NULL, 'labzak'),
  ('Dilshod Abdurahmonov', 'DILSHOD ABDURAHMONOV', 'individual', NULL, 'labzak'),
  ('Nazim', 'NAZIM', 'individual', NULL, 'labzak'),
  ('Rashid Gafurov', 'RASHID GAFUROV', 'individual', NULL, 'labzak'),
  ('Ozodjon Esonov', 'OZODJON ESONOV', 'individual', NULL, 'labzak'),
  ('Odilbek Ilhamov', 'ODILBEK ILHAMOV', 'individual', NULL, 'labzak'),
  ('Karina Fayzulina', 'KARINA FAYZULINA', 'individual', NULL, 'labzak'),
  ('ITECHART', 'ITECHART', 'company', NULL, 'labzak'),
  ('Hasan', 'HASAN', 'individual', NULL, 'labzak'),
  ('Sherzod Karimov (BuySell) + Islom Kasimov', 'SHERZOD KARIMOV (BUYSELL) + ISLOM KASIMOV', 'individual', NULL, 'labzak'),
  ('CHOWIS', 'CHOWIS', 'company', 'Healthcare', 'labzak'),
  ('Ilya Zhiltsov', 'ILYA ZHILTSOV', 'individual', NULL, 'labzak'),
  ('Varvara Kuzmetskaya', 'VARVARA KUZMETSKAYA', 'individual', NULL, 'labzak'),
  ('Aziz Murtazayev', 'AZIZ MURTAZAYEV', 'individual', NULL, 'labzak'),
  ('Ivan Borodulin', 'IVAN BORODULIN', 'individual', NULL, 'labzak'),
  ('Maksim Romonovskiy', 'MAKSIM ROMONOVSKIY', 'individual', NULL, 'labzak'),
  ('Anna Kulyayeva', 'ANNA KULYAYEVA', 'individual', NULL, 'labzak'),
  ('Sharifjon Nig''matov', 'SHARIFJON NIG''MATOV', 'individual', NULL, 'labzak'),
  ('Azizxo''ja Qodirov', 'AZIZXO''JA QODIROV', 'individual', NULL, 'labzak'),
  ('Farhod', 'FARHOD', 'individual', NULL, 'labzak'),
  ('KAMZAY LAW', 'KAMZAY LAW', 'company', NULL, 'labzak'),
  ('ONLINE STARTUP', 'ONLINE STARTUP', 'company', NULL, 'labzak'),
  ('EXPORTGROUP MINERALS', 'EXPORTGROUP MINERALS', 'company', NULL, 'labzak'),
  ('EXIM SUPPLY', 'EXIM SUPPLY', 'company', 'Logistics', 'labzak'),
  ('Islom Kasimjonov', 'ISLOM KASIMJONOV', 'individual', NULL, 'labzak'),
  ('Temur Umarov', 'TEMUR UMAROV', 'individual', NULL, 'labzak'),
  ('Doniyor Sotvoldiyev', 'DONIYOR SOTVOLDIYEV', 'individual', NULL, 'labzak'),
  ('IMAN MANAGING COMPANY', 'IMAN MANAGING COMPANY', 'company', NULL, 'labzak'),
  ('Teshayev Alisher', 'TESHAYEV ALISHER', 'company', NULL, 'labzak'),
  ('Oasis Audit+Ibrohimov Akmal', 'OASIS AUDIT+IBROHIMOV AKMAL', 'company', NULL, 'labzak'),
  ('EXADOT', 'EXADOT', 'company', NULL, 'labzak'),
  ('Sanjar Adizov 1', 'SANJAR ADIZOV 1', 'individual', NULL, 'labzak'),
  ('Sanjar Adizov 2', 'SANJAR ADIZOV 2', 'individual', NULL, 'labzak'),
  ('PEOPLEPAY U', 'PEOPLEPAY U', 'company', NULL, 'labzak'),
  ('Aziz Murtazaev', 'AZIZ MURTAZAEV', 'individual', NULL, 'labzak'),
  ('INSTANT PAYMENT SOLUTIONS', 'INSTANT PAYMENT SOLUTIONS', 'company', NULL, 'labzak'),
  ('ASSET MONETISATION GROUP', 'ASSET MONETISATION GROUP', 'company', NULL, 'labzak'),
  ('TOSHKENT MED TEX CA', 'TOSHKENT MED TEX CA', 'company', NULL, 'labzak'),
  ('IMPEX COMMUNITY', 'IMPEX COMMUNITY', 'company', NULL, 'labzak'),
  ('AZIYA-WELD GROUP', 'AZIYA-WELD GROUP', 'company', NULL, 'labzak'),
  ('FIN WELD-AZIYA', 'FIN WELD-AZIYA', 'company', NULL, 'labzak'),
  ('ALFA STAR CONSTRUCTOR', 'ALFA STAR CONSTRUCTOR', 'company', NULL, 'labzak'),
  ('Abdurahmon', 'ABDURAHMON', 'individual', NULL, 'labzak'),
  ('Gennadiy Team', 'GENNADIY TEAM', 'company', NULL, 'labzak'),
  ('Muhammadillo Team', 'MUHAMMADILLO TEAM', 'company', NULL, 'labzak'),
  ('ASXAB', 'ASXAB', 'company', NULL, 'labzak'),
  ('Ibrohim Akmalov', 'IBROHIM AKMALOV', 'individual', NULL, 'labzak'),
  ('Alisher Tilyayev', 'ALISHER TILYAYEV', 'individual', NULL, 'labzak'),
  ('QAMAR', 'QAMAR', 'company', NULL, 'labzak'),
  ('Aziz', 'AZIZ', 'company', NULL, 'labzak'),
  ('Kamolxon', 'KAMOLXON', 'individual', NULL, 'labzak'),
  ('DIZEGNO DESIGN AGENCY', 'DIZEGNO DESIGN AGENCY', 'company', NULL, 'labzak'),
  ('Islom Kasimjanov', 'ISLOM KASIMJANOV', 'individual', NULL, 'labzak'),
  ('Temur Mannonov', 'TEMUR MANNONOV', 'individual', NULL, 'labzak'),
  ('Hojiakbarbek Zokirbekov', 'HOJIAKBARBEK ZOKIRBEKOV', 'individual', NULL, 'labzak'),
  ('Oksana', 'OKSANA', 'individual', NULL, 'labzak'),
  ('Rozikov Anvar Xalilovich', 'ROZIKOV ANVAR XALILOVICH', 'individual', NULL, 'labzak'),
  ('Sardor Ergashev (Night 2x)', 'SARDOR ERGASHEV (NIGHT 2X)', 'individual', NULL, 'labzak'),
  ('CLEAN FIELD', 'CLEAN FIELD', 'company', NULL, 'labzak'),
  ('INHOST', 'INHOST', 'company', NULL, 'labzak'),
  ('SPORT STATISTICS', 'SPORT STATISTICS', 'company', NULL, 'labzak'),
  ('AZISIL', 'AZISIL', 'company', NULL, 'labzak'),
  ('SONDERS RETAIL', 'SONDERS RETAIL', 'company', NULL, 'labzak'),
  ('TECHCELLS', 'TECHCELLS', 'company', NULL, 'labzak'),
  ('GREAT BEST TRADE BIZNES', 'GREAT BEST TRADE BIZNES', 'company', NULL, 'labzak'),
  ('NWPSOFT', 'NWPSOFT', 'company', NULL, 'labzak'),
  ('Zulfiya', 'ZULFIYA', 'individual', NULL, 'labzak'),
  ('MAXLOADER', 'MAXLOADER', 'company', NULL, 'labzak'),
  ('REDWOOD PRO', 'REDWOOD PRO', 'company', NULL, 'labzak'),
  ('START TRADE AND TECHNOLOGY', 'START TRADE AND TECHNOLOGY', 'company', NULL, 'labzak'),
  ('DYNINNO TAS INTERNATIONAL', 'DYNINNO TAS INTERNATIONAL', 'company', NULL, 'labzak'),
  ('MT-AMBER KARVONI', 'MT-AMBER KARVONI', 'company', NULL, 'labzak'),
  ('DER PLATTENBAU', 'DER PLATTENBAU', 'company', NULL, 'labzak'),
  ('PLATFORMA GARANT', 'PLATFORMA GARANT', 'company', NULL, 'labzak'),
  ('MIDAS OPERATION', 'MIDAS OPERATION', 'company', NULL, 'labzak'),
  ('DELCREDA', 'DELCREDA', 'company', NULL, 'labzak'),
  ('NEXTMARK', 'NEXTMARK', 'company', NULL, 'labzak'),
  ('Qutbiddin Maxmudov', 'QUTBIDDIN MAXMUDOV', 'individual', NULL, 'labzak'),
  ('Alisher Ergashev', 'ALISHER ERGASHEV', 'individual', NULL, 'labzak'),
  ('Sherali Alikulov', 'SHERALI ALIKULOV', 'individual', NULL, 'labzak'),
  ('LAUTSTERN DC', 'LAUTSTERN DC', 'company', NULL, 'labzak'),
  ('Abdulbosit', 'ABDULBOSIT', 'individual', NULL, 'labzak'),
  ('Shuhrat Shernazarov', 'SHUHRAT SHERNAZAROV', 'individual', NULL, 'labzak'),
  ('HAVAS INDUSTRIZ', 'HAVAS INDUSTRIZ', 'company', NULL, 'labzak'),
  ('SPETZPOZH', 'SPETZPOZH', 'company', NULL, 'labzak'),
  ('STALNAY MARKA', 'STALNAY MARKA', 'company', NULL, 'labzak'),
  ('HAUL TRUCKS-CA', 'HAUL TRUCKS-CA', 'company', NULL, 'labzak'),
  ('TUERREDDA', 'TUERREDDA', 'company', NULL, 'labzak'),
  ('AYAM ROADS', 'AYAM ROADS', 'company', NULL, 'labzak'),
  ('MARS IT SCHOOL', 'MARS IT SCHOOL', 'company', NULL, 'labzak'),
  ('INDEX CONSULTING COMPANY', 'INDEX CONSULTING COMPANY', 'company', NULL, 'labzak'),
  ('Muhammadillo Team + Mirkomil Team', 'MUHAMMADILLO TEAM + MIRKOMIL TEAM', 'company', NULL, 'labzak'),
  ('Akmal Qilichev', 'AKMAL QILICHEV', 'individual', NULL, 'labzak'),
  ('MENTO EDTECH', 'MENTO EDTECH', 'company', NULL, 'labzak'),
  ('Diyorbek Turabaev', 'DIYORBEK TURABAEV', 'individual', NULL, 'labzak'),
  ('Mirilhom Team', 'MIRILHOM TEAM', 'company', NULL, 'labzak'),
  ('Sarvinoz Teacher', 'SARVINOZ TEACHER', 'individual', NULL, 'labzak'),
  ('Alexandr 2x ($200 + 2000 so''m)', 'ALEXANDR 2X ($200 + 2000 SO''M)', 'individual', NULL, 'labzak'),
  ('GEONA GROUP', 'GEONA GROUP', 'company', NULL, 'labzak'),
  ('VLS-COM', 'VLS-COM', 'company', NULL, 'labzak'),
  ('PS CLOUD SERVICES', 'PS CLOUD SERVICES', 'company', NULL, 'labzak'),
  ('Mirkomil Team', 'MIRKOMIL TEAM', 'individual', NULL, 'labzak'),
  ('Ulug''bek Salimov', 'ULUG''BEK SALIMOV', 'individual', NULL, 'labzak'),
  ('Bahodir', 'BAHODIR', 'individual', NULL, 'labzak'),
  ('Fadriyya', 'FADRIYYA', 'individual', NULL, 'labzak'),
  ('Denis Sharibo', 'DENIS SHARIBO', 'individual', NULL, 'labzak'),
  ('Dmitriy', 'DMITRIY', 'individual', NULL, 'labzak'),
  ('Aleksandr Makarov', 'ALEKSANDR MAKAROV', 'individual', NULL, 'labzak'),
  ('Maksim Tkachov', 'MAKSIM TKACHOV', 'individual', NULL, 'labzak'),
  ('Qutbiddin', 'QUTBIDDIN', 'individual', NULL, 'labzak'),
  ('Vladislav Sidyukov', 'VLADISLAV SIDYUKOV', 'individual', NULL, 'labzak'),
  ('GINZA SOFT', 'GINZA SOFT', 'company', NULL, 'labzak'),
  ('Azizbek Rasulov', 'AZIZBEK RASULOV', 'individual', NULL, 'labzak'),
  ('Anna', 'ANNA', 'individual', NULL, 'labzak'),
  ('Alexandr Xarlapanov', 'ALEXANDR XARLAPANOV', 'individual', NULL, 'labzak'),
  ('Ilya', 'ILYA', 'individual', NULL, 'labzak'),
  ('YO''LDOSH EXPORT', 'YO''LDOSH EXPORT', 'company', NULL, 'labzak'),
  ('MONTBLANC LOGISTICS', 'MONTBLANC LOGISTICS', 'company', NULL, 'labzak'),
  ('BALTICA-CA ALLIANCE', 'BALTICA-CA ALLIANCE', 'company', NULL, 'labzak'),
  ('DR-SIGMA', 'DR-SIGMA', 'company', 'Representative', 'labzak'),
  ('BEST LOGISTIC SOLUTION CA', 'BEST LOGISTIC SOLUTION CA', 'company', NULL, 'labzak'),
  ('SA MINERALS UBK', 'SA MINERALS UBK', 'company', NULL, 'labzak'),
  ('INTERPONT GRAND', 'INTERPONT GRAND', 'company', NULL, 'labzak'),
  ('PODVICK', 'PODVICK', 'company', NULL, 'labzak'),
  ('Shahzod Inomov', 'SHAHZOD INOMOV', 'individual', NULL, 'labzak'),
  ('Sabohat Shamshiyeva', 'SABOHAT SHAMSHIYEVA', 'individual', NULL, 'labzak'),
  ('Bahodir (Ayoli)', 'BAHODIR (AYOLI)', 'individual', NULL, 'labzak'),
  ('Aleksey Makarov', 'ALEKSEY MAKAROV', 'individual', NULL, 'labzak'),
  ('Dmitriy Nikolayevich', 'DMITRIY NIKOLAYEVICH', 'individual', NULL, 'labzak'),
  ('Anzor', 'ANZOR', 'individual', NULL, 'labzak'),
  ('Kristina Zabolotskaya', 'KRISTINA ZABOLOTSKAYA', 'individual', NULL, 'labzak'),
  ('Artyom Gladkix', 'ARTYOM GLADKIX', 'individual', NULL, 'labzak'),
  ('Vladimir Komarov', 'VLADIMIR KOMAROV', 'individual', NULL, 'labzak'),
  ('Ilya Zavaleev', 'ILYA ZAVALEEV', 'individual', NULL, 'labzak'),
  ('Anna Zavaleeva', 'ANNA ZAVALEEVA', 'individual', NULL, 'labzak'),
  ('RAPID SOLUTION', 'RAPID SOLUTION', 'company', NULL, 'labzak'),
  ('Ismatov Sohibjon', 'ISMATOV SOHIBJON', 'individual', NULL, 'labzak'),
  ('Andrey Sherbakov', 'ANDREY SHERBAKOV', 'individual', NULL, 'labzak'),
  ('Samandar Ochilov', 'SAMANDAR OCHILOV', 'individual', NULL, 'labzak'),
  ('Bek Bermurodov', 'BEK BERMURODOV', 'individual', NULL, 'labzak'),
  ('SOFTYSOL INTEGRATION', 'SOFTYSOL INTEGRATION', 'company', 'IT', 'labzak'),
  ('NOVA FUTURUM IT', 'NOVA FUTURUM IT', 'company', NULL, 'labzak'),
  ('KA FUTURE ENGINEERING', 'KA FUTURE ENGINEERING', 'company', NULL, 'labzak'),
  ('Adxam', 'ADXAM', 'individual', NULL, 'labzak'),
  ('AMC BRIDGE SOFTWARE', 'AMC BRIDGE SOFTWARE', 'company', NULL, 'labzak'),
  ('Sardor Nazirov', 'SARDOR NAZIROV', 'individual', NULL, 'labzak'),
  ('Konstantin Lavrentov', 'KONSTANTIN LAVRENTOV', 'individual', NULL, 'labzak'),
  ('Aleksey TR', 'ALEKSEY TR', 'individual', NULL, 'labzak'),
  ('Saidakbar Zafarov', 'SAIDAKBAR ZAFAROV', 'individual', NULL, 'labzak'),
  ('Xojiakbarbek Zokirbekov', 'XOJIAKBARBEK ZOKIRBEKOV', 'individual', NULL, 'labzak'),
  ('INN-TEX', 'INN-TEX', 'company', NULL, 'labzak'),
  ('LAZAREV ALEX', 'LAZAREV ALEX', 'company', NULL, 'labzak'),
  ('QUANTA NOVA', 'QUANTA NOVA', 'company', NULL, 'labzak'),
  ('TRINITY CENTER', 'TRINITY CENTER', 'company', NULL, 'labzak'),
  ('PARLAK IS', 'PARLAK IS', 'company', NULL, 'labzak'),
  ('SGGROUP-U', 'SGGROUP-U', 'company', NULL, 'labzak'),
  ('OOO «SA MINERALS UBK»', 'OOO «SA MINERALS UBK»', 'company', NULL, 'labzak'),
  ('OOO «EXADOT»', 'OOO «EXADOT»', 'company', NULL, 'labzak'),
  ('OOO «YOKO ELECTRIK»', 'OOO «YOKO ELECTRIK»', 'company', NULL, 'labzak'),
  ('Deposit', 'DEPOSIT', 'individual', NULL, 'labzak'),
  ('Other', 'OTHER', 'individual', NULL, 'labzak'),
  ('Night', 'NIGHT', 'individual', NULL, 'labzak'),
  ('Ziyod Abdurahimov', 'ZIYOD ABDURAHIMOV', 'individual', NULL, 'labzak'),
  ('Djonxon Djamilov', 'DJONXON DJAMILOV', 'individual', NULL, 'labzak'),
  ('Nurmuhammad', 'NURMUHAMMAD', 'individual', NULL, 'labzak'),
  ('Sergey Navruzov', 'SERGEY NAVRUZOV', 'individual', NULL, 'labzak'),
  ('Said Babajanov', 'SAID BABAJANOV', 'individual', NULL, 'labzak'),
  ('LAB GEMOTEST RU', 'LAB GEMOTEST RU', 'company', NULL, 'labzak'),
  ('TECH-HIVE', 'TECH-HIVE', 'company', NULL, 'labzak'),
  ('AMS VOSTOK ALLIANCE', 'AMS VOSTOK ALLIANCE', 'company', NULL, 'labzak'),
  ('SILKROADBUILD', 'SILKROADBUILD', 'company', NULL, 'labzak'),
  ('MEGAWATT MOTORS', 'MEGAWATT MOTORS', 'company', NULL, 'labzak'),
  ('INTERNATIONAL FOODCHAIN', 'INTERNATIONAL FOODCHAIN', 'company', NULL, 'labzak'),
  ('Akhmedjanov Shokhjakhon', 'AKHMEDJANOV SHOKHJAKHON', 'individual', NULL, 'labzak'),
  ('TDS MEDIA ONE', 'TDS MEDIA ONE', 'company', 'Marketing', 'labzak'),
  ('Mirsaid', 'MIRSAID', 'individual', NULL, 'labzak'),
  ('Abduvohid Axmedov', 'ABDUVOHID AXMEDOV', 'individual', NULL, 'labzak'),
  ('Nazirov Khasanjon', 'NAZIROV KHASANJON', 'individual', NULL, 'labzak'),
  ('Nazarov Sultonbek', 'NAZAROV SULTONBEK', 'individual', NULL, 'labzak'),
  ('Grigoriy', 'GRIGORIY', 'individual', NULL, 'labzak'),
  ('OPTO DELIVERY', 'OPTO DELIVERY', 'company', NULL, 'labzak'),
  ('JBF COMPONENTS', 'JBF COMPONENTS', 'company', NULL, 'labzak'),
  ('ALFA LINE', 'ALFA LINE', 'company', NULL, 'labzak'),
  ('Iroda opa', 'IRODA OPA', 'individual', NULL, 'labzak'),
  ('TURFALT', 'TURFALT', 'company', NULL, 'labzak'),
  ('BCLOUDS', 'BCLOUDS', 'company', NULL, 'labzak'),
  ('Shohjahon Hamdamov', 'SHOHJAHON HAMDAMOV', 'individual', NULL, 'labzak'),
  ('Sanjar Adizov (Exadot)', 'SANJAR ADIZOV (EXADOT)', 'individual', NULL, 'labzak'),
  ('LAVOROSOLUTIONS', 'LAVOROSOLUTIONS', 'company', NULL, 'labzak'),
  ('Behruz Rasulov', 'BEHRUZ RASULOV', 'individual', NULL, 'labzak'),
  ('Asadbek Abdurahmonov', 'ASADBEK ABDURAHMONOV', 'individual', NULL, 'labzak'),
  ('Mir Islom Akbarov', 'MIR ISLOM AKBAROV', 'individual', NULL, 'labzak'),
  ('BAKOTECH DISTRIBUTION', 'BAKOTECH DISTRIBUTION', 'company', NULL, 'labzak'),
  ('SMART SOLUTIONS INTERNATIONAL', 'SMART SOLUTIONS INTERNATIONAL', 'company', NULL, 'labzak'),
  ('GRAND-AERO-EXPORT', 'GRAND-AERO-EXPORT', 'company', NULL, 'labzak'),
  ('STONE CRAFTERS', 'STONE CRAFTERS', 'company', NULL, 'labzak'),
  ('BEL-WEST-CONSULT', 'BEL-WEST-CONSULT', 'company', NULL, 'labzak'),
  ('STANDARD STEEL CO', 'STANDARD STEEL CO', 'company', NULL, 'labzak'),
  ('LESECHKO ARSENIY SERGEYEVICH', 'LESECHKO ARSENIY SERGEYEVICH', 'company', NULL, 'labzak'),
  ('XI YUANG DONG TIEXTILE', 'XI YUANG DONG TIEXTILE', 'company', NULL, 'labzak'),
  ('VERTEX-KZ', 'VERTEX-KZ', 'company', NULL, 'labzak'),
  ('LANGO TRADING', 'LANGO TRADING', 'company', NULL, 'labzak'),
  ('Inomov Fazliddin', 'INOMOV FAZLIDDIN', 'individual', NULL, 'labzak'),
  ('Shaxzod', 'SHAXZOD', 'individual', NULL, 'labzak'),
  ('Ilxom', 'ILXOM', 'individual', NULL, 'labzak'),
  ('Toxir Murayev', 'TOXIR MURAYEV', 'individual', NULL, 'labzak'),
  ('Bexruz', 'BEXRUZ', 'individual', NULL, 'labzak'),
  ('Qosimov Said', 'QOSIMOV SAID', 'individual', NULL, 'labzak'),
  ('Jamshid', 'JAMSHID', 'individual', NULL, 'labzak'),
  ('Bekzod', 'BEKZOD', 'individual', NULL, 'labzak'),
  ('RIVL-LIMITED', 'RIVL-LIMITED', 'company', NULL, 'labzak'),
  ('TEXNOLAND GROUP TRADE', 'TEXNOLAND GROUP TRADE', 'company', NULL, 'labzak'),
  ('ALEKSEYEV YEVGENIY IGOREVICH', 'ALEKSEYEV YEVGENIY IGOREVICH', 'company', NULL, 'labzak'),
  ('Muzaffarov Bobir', 'MUZAFFAROV BOBIR', 'company', NULL, 'labzak'),
  ('MARKETLAB', 'MARKETLAB', 'company', NULL, 'labzak'),
  ('Kamilla Team', 'KAMILLA TEAM', 'individual', NULL, 'labzak'),
  ('Nafis Maxash', 'NAFIS MAXASH', 'individual', NULL, 'labzak'),
  ('ARGAYL', 'ARGAYL', 'company', NULL, 'labzak'),
  ('Nizomiddin', 'NIZOMIDDIN', 'individual', NULL, 'labzak'),
  ('Shaxzod Ayubov', 'SHAXZOD AYUBOV', 'individual', NULL, 'labzak'),
  ('Islom Jangobayev', 'ISLOM JANGOBAYEV', 'individual', NULL, 'labzak'),
  ('Shog''ulom Shohaydarov', 'SHOG''ULOM SHOHAYDAROV', 'individual', NULL, 'labzak'),
  ('Ilxom Maqsadov', 'ILXOM MAQSADOV', 'individual', NULL, 'labzak'),
  ('Abdulaziz Abdukarimov', 'ABDULAZIZ ABDUKARIMOV', 'individual', NULL, 'labzak'),
  ('Dilnoza Xamidulayeva', 'DILNOZA XAMIDULAYEVA', 'individual', NULL, 'labzak'),
  ('Ilhom Maqsadov', 'ILHOM MAQSADOV', 'individual', NULL, 'labzak'),
  ('Jamshid Abdusodiqov', 'JAMSHID ABDUSODIQOV', 'individual', NULL, 'labzak'),
  ('Abdurahim Abdurahimov', 'ABDURAHIM ABDURAHIMOV', 'individual', NULL, 'labzak'),
  ('Bekzod To''xtamuradov', 'BEKZOD TO''XTAMURADOV', 'individual', NULL, 'labzak'),
  ('ABRIS OPEN', 'ABRIS OPEN', 'company', NULL, 'labzak'),
  ('APS TECHNOLOGIA', 'APS TECHNOLOGIA', 'company', NULL, 'labzak'),
  ('GGIS INTEGRATSIYA', 'GGIS INTEGRATSIYA', 'company', NULL, 'labzak'),
  ('UNICUS PROPERTIES', 'UNICUS PROPERTIES', 'company', NULL, 'labzak'),
  ('SAYLIEV MATH', 'SAYLIEV MATH', 'company', NULL, 'labzak'),
  ('A MASTER FRUIT', 'A MASTER FRUIT', 'company', NULL, 'labzak'),
  ('Oqilbek', 'OQILBEK', 'individual', NULL, 'labzak'),
  ('Behruz aka', 'BEHRUZ AKA', 'individual', NULL, 'labzak'),
  ('SMARTU LABS', 'SMARTU LABS', 'company', NULL, 'labzak'),
  ('Abdurahim', 'ABDURAHIM', 'individual', NULL, 'labzak'),
  ('Artur Xafizov', 'ARTUR XAFIZOV', 'individual', NULL, 'labzak'),
  ('Irina Khvan', 'IRINA KHVAN', 'individual', NULL, 'labzak'),
  ('Bilol Isroilov', 'BILOL ISROILOV', 'individual', NULL, 'labzak'),
  ('Krill Gaynutdinov', 'KRILL GAYNUTDINOV', 'individual', NULL, 'labzak'),
  ('Muhammadkamron Sattorov', 'MUHAMMADKAMRON SATTOROV', 'individual', NULL, 'labzak'),
  ('Aleksandr Guruzintsev', 'ALEKSANDR GURUZINTSEV', 'individual', NULL, 'labzak'),
  ('Gavhar Yuldasheva', 'GAVHAR YULDASHEVA', 'individual', NULL, 'labzak'),
  ('Ilhom Maqsudqulov', 'ILHOM MAQSUDQULOV', 'individual', NULL, 'labzak'),
  ('Farhod Yo''ldoshev', 'FARHOD YO''LDOSHEV', 'individual', NULL, 'labzak'),
  ('Asror G''ofurov', 'ASROR G''OFUROV', 'individual', NULL, 'labzak'),
  ('Farruxjon', 'FARRUXJON', 'individual', NULL, 'labzak'),
  ('Sabohat', 'SABOHAT', 'individual', NULL, 'labzak'),
  ('DAVLAT AXBOROT TIZIMLARINI YARATISH VA QO`LLASH', 'DAVLAT AXBOROT TIZIMLARINI YARATISH VA QO`LLASH', 'company', NULL, 'labzak'),
  ('Siroj Saparbaev', 'SIROJ SAPARBAEV', 'individual', NULL, 'labzak'),
  ('Sanjar aka', 'SANJAR AKA', 'individual', NULL, 'labzak'),
  ('Ilya Zavalev', 'ILYA ZAVALEV', 'individual', NULL, 'labzak'),
  ('Anna Zavaleva', 'ANNA ZAVALEVA', 'individual', NULL, 'labzak'),
  ('Munira Ismatova', 'MUNIRA ISMATOVA', 'individual', NULL, 'labzak'),
  ('Alisher Teshaev', 'ALISHER TESHAEV', 'individual', NULL, 'labzak'),
  ('Zokir Umedov', 'ZOKIR UMEDOV', 'individual', NULL, 'labzak'),
  ('Ruslan Ramazanov', 'RUSLAN RAMAZANOV', 'individual', NULL, 'labzak'),
  ('Mirpo''lat Mirakbarov', 'MIRPO''LAT MIRAKBAROV', 'individual', NULL, 'labzak'),
  ('Hurshid Mamatov', 'HURSHID MAMATOV', 'individual', NULL, 'labzak'),
  ('Begzod To''xtamurodov', 'BEGZOD TO''XTAMURODOV', 'individual', NULL, 'labzak'),
  ('Hayot Yadgorov', 'HAYOT YADGOROV', 'individual', NULL, 'labzak'),
  ('Siroj Boboyev', 'SIROJ BOBOYEV', 'individual', NULL, 'labzak'),
  ('Abdurauf Sherkulov', 'ABDURAUF SHERKULOV', 'individual', NULL, 'labzak'),
  ('Mustafa Azizyar', 'MUSTAFA AZIZYAR', 'individual', NULL, 'labzak'),
  ('IT FOR ENTERPRICE', 'IT FOR ENTERPRICE', 'company', NULL, 'labzak'),
  ('VISA TASHKENT', 'VISA TASHKENT', 'company', NULL, 'labzak'),
  ('MAYPHIL CA', 'MAYPHIL CA', 'company', NULL, 'labzak'),
  ('CARBO RESOURCE', 'CARBO RESOURCE', 'company', NULL, 'labzak'),
  ('KETRING', 'KETRING', 'company', NULL, 'labzak'),
  ('ORZU-FINTECH', 'ORZU-FINTECH', 'company', NULL, 'labzak'),
  ('ISKANDAR-NUR', 'ISKANDAR-NUR', 'company', NULL, 'labzak'),
  ('Samandar Mirahmedov', 'SAMANDAR MIRAHMEDOV', 'individual', NULL, 'labzak'),
  ('Alexandr Zlenko', 'ALEXANDR ZLENKO', 'individual', NULL, 'labzak'),
  ('Sabohat Kalandarova', 'SABOHAT KALANDAROVA', 'individual', NULL, 'labzak'),
  ('Li Sergey Evgenovich', 'LI SERGEY EVGENOVICH', 'individual', NULL, 'labzak'),
  ('Nazir Nazirov', 'NAZIR NAZIROV', 'individual', NULL, 'labzak'),
  ('MIGRANT', 'MIGRANT', 'company', NULL, 'labzak'),
  ('WORLD MEGA-SALE', 'WORLD MEGA-SALE', 'company', NULL, 'labzak'),
  ('FOM GROUP', 'FOM GROUP', 'company', NULL, 'labzak'),
  ('YES CONSULTING', 'YES CONSULTING', 'company', NULL, 'labzak'),
  ('Bunyod', 'BUNYOD', 'individual', NULL, 'labzak'),
  ('Jonibek Ergashev', 'JONIBEK ERGASHEV', 'individual', NULL, 'labzak'),
  ('Charos Sobirova', 'CHAROS SOBIROVA', 'individual', NULL, 'labzak'),
  ('Kirill', 'KIRILL', 'individual', NULL, 'labzak'),
  ('Miralisher Xonjanov', 'MIRALISHER XONJANOV', 'individual', NULL, 'labzak'),
  ('Media tadqiqotlari va ta`lim ishlanmalari', 'MEDIA TADQIQOTLARI VA TA`LIM ISHLANMALARI', 'company', NULL, 'labzak'),
  ('METSOL', 'METSOL', 'company', NULL, 'labzak'),
  ('Adxamxujayev Nodirxoja', 'ADXAMXUJAYEV NODIRXOJA', 'individual', NULL, 'labzak'),
  ('Bekzod Avazbekov', 'BEKZOD AVAZBEKOV', 'individual', NULL, 'labzak'),
  ('ELEKTROBREND SOLUTIONS', 'ELEKTROBREND SOLUTIONS', 'company', NULL, 'labzak'),
  ('SECURE SECTOR', 'SECURE SECTOR', 'company', NULL, 'labzak'),
  ('Xumoyun Logist', 'XUMOYUN LOGIST', 'individual', NULL, 'labzak'),
  ('Islom Jangaboyev', 'ISLOM JANGABOYEV', 'individual', NULL, 'labzak'),
  ('Ibragimov Rovshan', 'IBRAGIMOV ROVSHAN', 'individual', NULL, 'labzak'),
  ('Ozeranskiy Sergey', 'OZERANSKIY SERGEY', 'individual', NULL, 'labzak'),
  ('Asanova Sevilya', 'ASANOVA SEVILYA', 'individual', NULL, 'labzak'),
  ('GEONA-GROUP', 'GEONA-GROUP', 'company', NULL, 'labzak'),
  ('STAR TRADE AND TECHNOLOGY', 'STAR TRADE AND TECHNOLOGY', 'company', NULL, 'labzak'),
  ('RIVL LIMITED', 'RIVL LIMITED', 'company', NULL, 'labzak'),
  ('SOB CLUB', 'SOB CLUB', 'company', NULL, 'labzak'),
  ('CARGON CA', 'CARGON CA', 'company', NULL, 'labzak'),
  ('AMERICAN COUNCILS', 'AMERICAN COUNCILS', 'company', NULL, 'labzak'),
  ('WOLT', 'WOLT', 'company', NULL, 'labzak'),
  ('Behruz Pulatov', 'BEHRUZ PULATOV', 'individual', NULL, 'labzak'),
  ('HPBS', 'HPBS', 'company', NULL, 'labzak'),
  ('Mirsaid Ravilov', 'MIRSAID RAVILOV', 'individual', NULL, 'labzak'),
  ('Kabilova Dilsora', 'KABILOVA DILSORA', 'individual', NULL, 'labzak'),
  ('Kirill Gainutdinov', 'KIRILL GAINUTDINOV', 'individual', NULL, 'labzak'),
  ('Davletova Sevara', 'DAVLETOVA SEVARA', 'individual', NULL, 'labzak'),
  ('Abdulloh Jamilov', 'ABDULLOH JAMILOV', 'individual', NULL, 'labzak'),
  ('Shokirov Bunyod', 'SHOKIROV BUNYOD', 'individual', NULL, 'labzak'),
  ('KAPITAL MEDIAGROUP', 'KAPITAL MEDIAGROUP', 'company', NULL, 'labzak'),
  ('ALL TECH NDT', 'ALL TECH NDT', 'company', NULL, 'labzak'),
  ('NIPTS GNT', 'NIPTS GNT', 'company', NULL, 'labzak'),
  ('COSMOS BOOKS', 'COSMOS BOOKS', 'company', NULL, 'labzak'),
  ('ALPHA OMEGA MARKETING', 'ALPHA OMEGA MARKETING', 'company', NULL, 'labzak'),
  ('STAFAR EMPLOYMENT', 'STAFAR EMPLOYMENT', 'company', NULL, 'labzak'),
  ('Sherzod Ustoz Media', 'SHERZOD USTOZ MEDIA', 'individual', NULL, 'labzak'),
  ('Lazizxon Sodiqov', 'LAZIZXON SODIQOV', 'individual', NULL, 'labzak'),
  ('Ilyos Toxirov', 'ILYOS TOXIROV', 'individual', NULL, 'labzak'),
  ('Darya Kudryaseva', 'DARYA KUDRYASEVA', 'individual', NULL, 'labzak'),
  ('Nuriddin Muhitdinov', 'NURIDDIN MUHITDINOV', 'individual', NULL, 'labzak'),
  ('C-SPACE YUNUSABAD', 'C-SPACE YUNUSABAD', 'company', NULL, 'labzak'),
  ('Ibragimov Kamol', 'IBRAGIMOV KAMOL', 'individual', NULL, 'labzak'),
  ('Gulhayo Asxaab', 'GULHAYO ASXAAB', 'individual', NULL, 'labzak'),
  ('Anton Kostyuchenko', 'ANTON KOSTYUCHENKO', 'individual', NULL, 'labzak'),
  ('Ibrohim Alimuhammedov', 'IBROHIM ALIMUHAMMEDOV', 'individual', NULL, 'labzak'),
  ('Tojieva Marjona', 'TOJIEVA MARJONA', 'individual', NULL, 'labzak'),
  ('Oybek Dadashev', 'OYBEK DADASHEV', 'individual', NULL, 'labzak'),
  ('Lina Sedad', 'LINA SEDAD', 'individual', NULL, 'labzak'),
  ('HUDSON SANDLER', 'HUDSON SANDLER', 'company', NULL, 'labzak'),
  ('GO MUSIC APPS', 'GO MUSIC APPS', 'company', NULL, 'labzak'),
  ('Omadillo Parpiev', 'OMADILLO PARPIEV', 'individual', NULL, 'labzak'),
  ('Farhod Atajonov', 'FARHOD ATAJONOV', 'individual', NULL, 'labzak'),
  ('Azizbek Sadriddinov', 'AZIZBEK SADRIDDINOV', 'individual', NULL, 'labzak'),
  ('Fizur Kabilov', 'FIZUR KABILOV', 'individual', NULL, 'labzak'),
  ('Mirg''iyosiddin Turganov', 'MIRG''IYOSIDDIN TURGANOV', 'individual', NULL, 'labzak'),
  ('AMERIKA KENGASHI', 'AMERIKA KENGASHI', 'company', NULL, 'labzak'),
  ('Shuhrat Bahodirov', 'SHUHRAT BAHODIROV', 'individual', NULL, 'labzak'),
  ('KWAAKA', 'KWAAKA', 'company', NULL, 'labzak'),
  ('Suhrob Jamolov', 'SUHROB JAMOLOV', 'individual', NULL, 'labzak'),
  ('Elbek Normurodov', 'ELBEK NORMURODOV', 'individual', NULL, 'labzak'),
  ('Mirg''iyosiddin Turgunov', 'MIRG''IYOSIDDIN TURGUNOV', 'individual', NULL, 'labzak'),
  ('Sherzod', 'SHERZOD', 'individual', NULL, 'labzak'),
  ('ATTECH GLOBAL', 'ATTECH GLOBAL', 'company', NULL, 'labzak'),
  ('TURECODE', 'TURECODE', 'company', NULL, 'labzak'),
  ('AUTONOMICA VENTURES', 'AUTONOMICA VENTURES', 'company', NULL, 'labzak'),
  ('ECONOM COFFEE', 'ECONOM COFFEE', 'company', NULL, 'labzak'),
  ('UNITEL', 'UNITEL', 'company', NULL, 'labzak'),
  ('VIRTUAL PLATFORMS', 'VIRTUAL PLATFORMS', 'company', NULL, 'labzak'),
  ('APEXPRO', 'APEXPRO', 'company', NULL, 'labzak'),
  ('Toxirov Bilol Alixon', 'TOXIROV BILOL ALIXON', 'individual', NULL, 'labzak'),
  ('Shodmonov Aziz', 'SHODMONOV AZIZ', 'individual', NULL, 'labzak'),
  ('Abdusodiqov Jamshid', 'ABDUSODIQOV JAMSHID', 'individual', NULL, 'labzak'),
  ('Mehmet Yazar', 'MEHMET YAZAR', 'individual', NULL, 'labzak'),
  ('Toybayov Ersultan', 'TOYBAYOV ERSULTAN', 'individual', NULL, 'labzak'),
  ('Sayfuddinov A''lo', 'SAYFUDDINOV A''LO', 'individual', NULL, 'labzak'),
  ('Sultonov Muhammad Orif', 'SULTONOV MUHAMMAD ORIF', 'individual', NULL, 'labzak'),
  ('Murod Gayratov', 'MUROD GAYRATOV', 'individual', NULL, 'labzak'),
  ('WOLT TEXNOLOGIYALARI', 'WOLT TEXNOLOGIYALARI', 'company', NULL, 'labzak'),
  ('AFSUN TRADING', 'AFSUN TRADING', 'company', NULL, 'labzak'),
  ('FRESH TOUR', 'FRESH TOUR', 'company', NULL, 'labzak'),
  ('APOLLO TRAVEL', 'APOLLO TRAVEL', 'company', NULL, 'labzak'),
  ('Shaxzod Ayubjonov', 'SHAXZOD AYUBJONOV', 'individual', NULL, 'labzak'),
  ('Safarov Ismoil', 'SAFAROV ISMOIL', 'individual', NULL, 'labzak'),
  ('Олег', 'ОЛЕГ', 'individual', NULL, 'labzak'),
  ('Normurodov Elbek', 'NORMURODOV ELBEK', 'individual', NULL, 'labzak'),
  ('Turganov Mirg''iyosiddin', 'TURGANOV MIRG''IYOSIDDIN', 'individual', NULL, 'labzak'),
  ('Хурщид', 'ХУРЩИД', 'individual', NULL, 'labzak'),
  ('Tahirov Ilyos', 'TAHIROV ILYOS', 'individual', NULL, 'labzak'),
  ('WYZO', 'WYZO', 'company', NULL, 'labzak'),
  ('ICC OILS AND FATS TAS', 'ICC OILS AND FATS TAS', 'company', NULL, 'labzak'),
  ('PROMET', 'PROMET', 'company', NULL, 'labzak'),
  ('ENDORPHIN ADVERTISING', 'ENDORPHIN ADVERTISING', 'company', NULL, 'labzak'),
  ('XASANOVA MADINA UMARJON QIZI', 'XASANOVA MADINA UMARJON QIZI', 'company', NULL, 'labzak'),
  ('RECALL CORP', 'RECALL CORP', 'company', NULL, 'labzak'),
  ('TURON TELECOM', 'TURON TELECOM', 'company', NULL, 'labzak'),
  ('TEZ IT SOLUTIONS', 'TEZ IT SOLUTIONS', 'company', NULL, 'labzak'),
  ('Xurshid Logist', 'XURSHID LOGIST', 'individual', NULL, 'labzak'),
  ('Munisa Nizamova', 'MUNISA NIZAMOVA', 'individual', NULL, 'labzak'),
  ('Oleg Sukanov', 'OLEG SUKANOV', 'individual', NULL, 'labzak'),
  ('MARKAZIY OSIYOFINTEX ASSOTSIATSIYASI', 'MARKAZIY OSIYOFINTEX ASSOTSIATSIYASI', 'company', NULL, 'labzak'),
  ('ROCKY RIDGE SOFTWARE', 'ROCKY RIDGE SOFTWARE', 'company', NULL, 'labzak'),
  ('AlFA TURK', 'ALFA TURK', 'company', NULL, 'labzak'),
  ('FEEDUP ECO', 'FEEDUP ECO', 'company', NULL, 'labzak'),
  ('Abdirahimov Zuyod', 'ABDIRAHIMOV ZUYOD', 'company', NULL, 'labzak'),
  ('Хуршид', 'ХУРШИД', 'individual', NULL, 'labzak'),
  ('TASK IYN', 'TASK IYN', 'company', NULL, 'labzak'),
  ('Qayumov Bekzod', 'QAYUMOV BEKZOD', 'individual', NULL, 'labzak'),
  ('Xudayberganov Abdumamin', 'XUDAYBERGANOV ABDUMAMIN', 'individual', NULL, 'labzak'),
  ('AG CREATIONS', 'AG CREATIONS', 'company', NULL, 'labzak'),
  ('NEW UZBEKISTAN MINING', 'NEW UZBEKISTAN MINING', 'company', NULL, 'labzak'),
  ('INNOSPHERE', 'INNOSPHERE', 'company', NULL, 'labzak'),
  ('UNIPRO-AZ', 'UNIPRO-AZ', 'company', NULL, 'labzak'),
  ('Xojiakbar Zokirbekov', 'XOJIAKBAR ZOKIRBEKOV', 'individual', NULL, 'labzak'),
  ('Jorayev JahongirMirzo', 'JORAYEV JAHONGIRMIRZO', 'individual', NULL, 'labzak'),
  ('Shahzod Rustamjon', 'SHAHZOD RUSTAMJON', 'individual', NULL, 'labzak'),
  ('sattorov ismoiljon', 'SATTOROV ISMOILJON', 'individual', NULL, 'labzak'),
  ('MANSURBEK BIZNES IMKONI', 'MANSURBEK BIZNES IMKONI', 'company', NULL, 'labzak'),
  ('TIMELESS', 'TIMELESS', 'company', NULL, 'labzak'),
  ('SAINT-GOBAIN CONSTRUCTION PRODUCTS CAU', 'SAINT-GOBAIN CONSTRUCTION PRODUCTS CAU', 'company', NULL, 'labzak'),
  ('GEOSTRATA', 'GEOSTRATA', 'company', NULL, 'labzak'),
  ('NASRULLO QURULISH TORG', 'NASRULLO QURULISH TORG', 'company', NULL, 'labzak'),
  ('TEREA', 'TEREA', 'company', NULL, 'labzak'),
  ('KAMILLAXON DOKONI', 'KAMILLAXON DOKONI', 'company', NULL, 'labzak'),
  ('NAZ-OZ', 'NAZ-OZ', 'company', NULL, 'labzak'),
  ('TOP-IT', 'TOP-IT', 'company', NULL, 'labzak'),
  ('RAFEX', 'RAFEX', 'company', NULL, 'labzak'),
  ('Xalilov Azizbek', 'XALILOV AZIZBEK', 'individual', NULL, 'labzak'),
  ('Sattorov Ismoiljin', 'SATTOROV ISMOILJIN', 'individual', NULL, 'labzak'),
  ('Okkiziyeva Dildora', 'OKKIZIYEVA DILDORA', 'individual', NULL, 'labzak'),
  ('Umarov Doston', 'UMAROV DOSTON', 'individual', NULL, 'labzak'),
  ('Zafar Sattorov', 'ZAFAR SATTOROV', 'individual', NULL, 'labzak'),
  ('INDUSTRIAL GROUP ENERGY EAST', 'INDUSTRIAL GROUP ENERGY EAST', 'company', NULL, 'labzak'),
  ('Sergey Pan', 'SERGEY PAN', 'individual', NULL, 'labzak'),
  ('BEST SOFT SALES', 'BEST SOFT SALES', 'company', NULL, 'labzak'),
  ('TAVAN BOGD NURA', 'TAVAN BOGD NURA', 'company', NULL, 'labzak'),
  ('BAI’SOFTWARE', 'BAI’SOFTWARE', 'company', NULL, 'labzak'),
  ('ZARAFSHAN BRIDGE TV', 'ZARAFSHAN BRIDGE TV', 'company', NULL, 'labzak'),
  ('Nabijonov Jasurbek', 'NABIJONOV JASURBEK', 'individual', NULL, 'labzak'),
  ('Finashin Maksim', 'FINASHIN MAKSIM', 'individual', NULL, 'labzak'),
  ('Jahongir Mirzo', 'JAHONGIR MIRZO', 'individual', NULL, 'labzak'),
  ('Bobur Asrorov', 'BOBUR ASROROV', 'individual', NULL, 'labzak'),
  ('Okkuziyeva Dildora', 'OKKUZIYEVA DILDORA', 'individual', NULL, 'labzak'),
  ('Kurbanova Nigora', 'KURBANOVA NIGORA', 'individual', NULL, 'labzak'),
  ('Dadashev Oybek', 'DADASHEV OYBEK', 'individual', NULL, 'labzak'),
  ('Nasrullo Shukrullayev', 'NASRULLO SHUKRULLAYEV', 'individual', NULL, 'labzak'),
  ('Kandirov Stanislav', 'KANDIROV STANISLAV', 'individual', NULL, 'labzak'),
  ('BFG INTERNATIONAL', 'BFG INTERNATIONAL', 'company', NULL, 'labzak'),
  ('TRANSPORT NEXUS', 'TRANSPORT NEXUS', 'company', NULL, 'labzak'),
  ('MWWALLET', 'MWWALLET', 'company', NULL, 'labzak'),
  ('YUNONA MERKURIY', 'YUNONA MERKURIY', 'company', NULL, 'labzak'),
  ('IKURA', 'IKURA', 'company', NULL, 'labzak'),
  ('ENDCODE', 'ENDCODE', 'company', NULL, 'labzak'),
  ('GRAVITY BAR', 'GRAVITY BAR', 'company', NULL, 'labzak'),
  ('Azizbek Parpiyev', 'AZIZBEK PARPIYEV', 'individual', NULL, 'labzak'),
  ('Ismoil Safarov', 'ISMOIL SAFAROV', 'individual', NULL, 'labzak'),
  ('Jamshid Almetov', 'JAMSHID ALMETOV', 'individual', NULL, 'labzak'),
  ('Fayzullayev Islom', 'FAYZULLAYEV ISLOM', 'individual', NULL, 'labzak'),
  ('Jamolov Samandar', 'JAMOLOV SAMANDAR', 'individual', NULL, 'labzak'),
  ('Yusupov Sunnat', 'YUSUPOV SUNNAT', 'individual', NULL, 'labzak'),
  ('Abdurahimov Sadriddin', 'ABDURAHIMOV SADRIDDIN', 'individual', NULL, 'labzak'),
  ('Vaisboyev Asilbek', 'VAISBOYEV ASILBEK', 'individual', NULL, 'labzak'),
  ('Xayrullayeva Surayyo', 'XAYRULLAYEVA SURAYYO', 'individual', NULL, 'labzak'),
  ('MOBILE DIGITAL DESIGN AGANCY', 'MOBILE DIGITAL DESIGN AGANCY', 'company', NULL, 'labzak'),
  ('TEHBURSERVICE', 'TEHBURSERVICE', 'company', NULL, 'labzak'),
  ('WELMONDE DIGITAL HEALTHCARE', 'WELMONDE DIGITAL HEALTHCARE', 'company', NULL, 'labzak'),
  ('GK IZI GROUP', 'GK IZI GROUP', 'company', NULL, 'labzak'),
  ('METRICA AGENCY', 'METRICA AGENCY', 'company', NULL, 'labzak'),
  ('Jamshid Almatov', 'JAMSHID ALMATOV', 'individual', NULL, 'labzak'),
  ('Belousov Igor', 'BELOUSOV IGOR', 'individual', NULL, 'labzak'),
  ('Gayratov Murod', 'GAYRATOV MUROD', 'individual', NULL, 'labzak'),
  ('Asadbek Xayrullayev', 'ASADBEK XAYRULLAYEV', 'individual', NULL, 'labzak'),
  ('Sadriddin Abdurahimov', 'SADRIDDIN ABDURAHIMOV', 'individual', NULL, 'labzak'),
  ('Asilbek vaisboyev', 'ASILBEK VAISBOYEV', 'individual', NULL, 'labzak'),
  ('DATATRUCK', 'DATATRUCK', 'company', NULL, 'labzak'),
  ('LOPUXOV VADIM', 'LOPUXOV VADIM', 'company', NULL, 'labzak'),
  ('CS Yunusabad', 'CS YUNUSABAD', 'company', NULL, 'labzak'),
  ('Smartpost', 'SMARTPOST', 'company', NULL, 'labzak'),
  ('expert imigartion sentr', 'EXPERT IMIGARTION SENTR', 'company', NULL, 'labzak'),
  ('Mashrapov Yaxyo', 'MASHRAPOV YAXYO', 'individual', NULL, 'labzak'),
  ('Mahmudov Saidazim', 'MAHMUDOV SAIDAZIM', 'individual', NULL, 'labzak'),
  ('Quvondiqov Javohir', 'QUVONDIQOV JAVOHIR', 'individual', NULL, 'labzak'),
  ('Nekrasov', 'NEKRASOV', 'company', NULL, 'labzak'),
  ('NAVKAR', 'NAVKAR', 'company', NULL, 'labzak'),
  ('TAKII SEED FERGANA', 'TAKII SEED FERGANA', 'company', NULL, 'labzak'),
  ('BILIMGURU', 'BILIMGURU', 'company', NULL, 'labzak'),
  ('cifrotech ca', 'CIFROTECH CA', 'company', NULL, 'labzak'),
  ('Lazizhon Sodiqov', 'LAZIZHON SODIQOV', 'individual', NULL, 'labzak'),
  ('kamolov xusan', 'KAMOLOV XUSAN', 'individual', NULL, 'labzak'),
  ('Abdulaziz Xontorayev', 'ABDULAZIZ XONTORAYEV', 'individual', NULL, 'labzak'),
  ('Dadaxanova Saida', 'DADAXANOVA SAIDA', 'individual', NULL, 'labzak'),
  ('ASAR', 'ASAR', 'company', NULL, 'labzak'),
  ('FARBAHOUSE-CA', 'FARBAHOUSE-CA', 'company', NULL, 'labzak'),
  ('AVIATION WEBSITE', 'AVIATION WEBSITE', 'company', NULL, 'labzak'),
  ('CONCEPT EVOLUTION', 'CONCEPT EVOLUTION', 'company', NULL, 'labzak'),
  ('Quality Service Future', 'QUALITY SERVICE FUTURE', 'company', NULL, 'labzak'),
  ('Wtraining', 'WTRAINING', 'company', NULL, 'labzak'),
  ('SHARIF MAXSULOTI', 'SHARIF MAXSULOTI', 'company', NULL, 'labzak'),
  ('abdulkayumov baxadir', 'ABDULKAYUMOV BAXADIR', 'individual', NULL, 'labzak'),
  ('Umid dedicated', 'UMID DEDICATED', 'individual', NULL, 'labzak'),
  ('ALEKSEY', 'ALEKSEY', 'individual', NULL, 'labzak'),
  ('SULAYMON', 'SULAYMON', 'individual', NULL, 'labzak'),
  ('SAIDAZAM MAHMUDOV', 'SAIDAZAM MAHMUDOV', 'individual', NULL, 'labzak'),
  ('DOSTON ERKINBOYEV', 'DOSTON ERKINBOYEV', 'individual', NULL, 'labzak'),
  ('Aleksandor Travin', 'ALEKSANDOR TRAVIN', 'individual', NULL, 'labzak'),
  ('YAXYO MASHRAPOV', 'YAXYO MASHRAPOV', 'individual', NULL, 'labzak'),
  ('tursunov abdulbois', 'TURSUNOV ABDULBOIS', 'individual', NULL, 'labzak'),
  ('bobur jorayev', 'BOBUR JORAYEV', 'individual', NULL, 'labzak'),
  ('INGRI', 'INGRI', 'company', NULL, 'labzak'),
  ('ACE GROUP CONSULTANTS-HR PARTNERS', 'ACE GROUP CONSULTANTS-HR PARTNERS', 'company', NULL, 'labzak'),
  ('Abdulhakimov Islombek', 'ABDULHAKIMOV ISLOMBEK', 'company', NULL, 'labzak'),
  ('Abror Abdukadirov', 'ABROR ABDUKADIROV', 'individual', NULL, 'labzak'),
  ('ATAY', 'ATAY', 'company', NULL, 'labzak'),
  ('Xasanboy Xalilov', 'XASANBOY XALILOV', 'individual', NULL, 'labzak'),
  ('suhrob', 'SUHROB', 'individual', NULL, 'labzak'),
  ('SAMANDAR JAMOLOV', 'SAMANDAR JAMOLOV', 'individual', NULL, 'labzak'),
  ('Xaqberdiyev Javohir', 'XAQBERDIYEV JAVOHIR', 'individual', NULL, 'labzak'),
  ('abdulbois tursunov', 'ABDULBOIS TURSUNOV', 'individual', NULL, 'labzak'),
  ('Murod Erkinboyev', 'MUROD ERKINBOYEV', 'individual', NULL, 'labzak'),
  ('Dildora', 'DILDORA', 'individual', NULL, 'labzak'),
  ('LS CARGO LOGISTIK', 'LS CARGO LOGISTIK', 'company', NULL, 'labzak'),
  ('BE WOMAN HAPPY WOMANS ACADEMY', 'BE WOMAN HAPPY WOMANS ACADEMY', 'company', NULL, 'labzak'),
  ('PGM RESOURCE CA', 'PGM RESOURCE CA', 'company', NULL, 'labzak'),
  ('MUSAIT TECH', 'MUSAIT TECH', 'company', NULL, 'labzak'),
  ('FIXORA', 'FIXORA', 'company', NULL, 'labzak'),
  ('COMFORTHOLD', 'COMFORTHOLD', 'company', NULL, 'labzak'),
  ('ibroxim botirov', 'IBROXIM BOTIROV', 'individual', NULL, 'labzak'),
  ('jasurbek nabijonov', 'JASURBEK NABIJONOV', 'individual', NULL, 'labzak'),
  ('umid', 'UMID', 'individual', NULL, 'labzak'),
  ('Hasanboy Halilov', 'HASANBOY HALILOV', 'individual', NULL, 'labzak'),
  ('saidazim maxmudov', 'SAIDAZIM MAXMUDOV', 'individual', NULL, 'labzak'),
  ('ozoda axmedova', 'OZODA AXMEDOVA', 'individual', NULL, 'labzak'),
  ('Sulaymon Xushnudov', 'SULAYMON XUSHNUDOV', 'individual', NULL, 'labzak'),
  ('ortiqova nihola', 'ORTIQOVA NIHOLA', 'individual', NULL, 'labzak'),
  ('javohir', 'JAVOHIR', 'individual', NULL, 'labzak'),
  ('DSMI MADENCILIK', 'DSMI MADENCILIK', 'company', NULL, 'labzak'),
  ('NAIM GOURMET', 'NAIM GOURMET', 'company', NULL, 'labzak'),
  ('CSS CA', 'CSS CA', 'company', NULL, 'labzak'),
  ('MAKMART EAST', 'MAKMART EAST', 'company', NULL, 'labzak'),
  ('LUMIKIDY', 'LUMIKIDY', 'company', NULL, 'labzak'),
  ('UNOMED', 'UNOMED', 'company', NULL, 'labzak'),
  ('EGBE', 'EGBE', 'company', NULL, 'labzak'),
  ('АМЕРИКАНСКИЕ СОВЕТЫ ПО МЕЖДУНАРОДНОМУ ОБРАЗОВАНИЮ В РЕСПУБЛИКЕ УЗБЕКИСТАН', 'АМЕРИКАНСКИЕ СОВЕТЫ ПО МЕЖДУНАРОДНОМУ ОБРАЗОВАНИЮ В РЕСПУБЛИКЕ УЗБЕКИСТАН', 'company', NULL, 'labzak'),
  ('Pharemberg', 'PHAREMBERG', 'company', NULL, 'labzak'),
  ('Core Global', 'CORE GLOBAL', 'company', NULL, 'labzak'),
  ('Sayidazim Maxmudov', 'SAYIDAZIM MAXMUDOV', 'individual', NULL, 'labzak'),
  ('Aziza', 'AZIZA', 'individual', NULL, 'labzak'),
  ('dildora okkuziyeva', 'DILDORA OKKUZIYEVA', 'individual', NULL, 'labzak'),
  ('JAHONGIRMIRZO JO''RAYEV', 'JAHONGIRMIRZO JO''RAYEV', 'individual', NULL, 'labzak'),
  ('Jahongir', 'JAHONGIR', 'individual', NULL, 'labzak'),
  ('ravshan Raimov', 'RAVSHAN RAIMOV', 'individual', NULL, 'labzak'),
  ('Nozima Xabibullayeva', 'NOZIMA XABIBULLAYEVA', 'individual', NULL, 'labzak'),
  ('IBCCS TAX', 'IBCCS TAX', 'company', NULL, 'labzak'),
  ('THEMAESTRO STUDIO', 'THEMAESTRO STUDIO', 'company', NULL, 'labzak'),
  ('ZENOFT', 'ZENOFT', 'company', NULL, 'labzak'),
  ('RADIANCE GROUP', 'RADIANCE GROUP', 'company', NULL, 'labzak'),
  ('WHITE HILL CAPITAL', 'WHITE HILL CAPITAL', 'company', NULL, 'labzak'),
  ('MASTERY PHARMA', 'MASTERY PHARMA', 'company', NULL, 'labzak'),
  ('UNION CAFE', 'UNION CAFE', 'company', NULL, 'labzak'),
  ('MSECURITY', 'MSECURITY', 'company', NULL, 'labzak'),
  ('PRIMAVERA TRADE', 'PRIMAVERA TRADE', 'company', NULL, 'labzak'),
  ('Ibrohim Botirov', 'IBROHIM BOTIROV', 'individual', NULL, 'labzak'),
  ('Xasan xalilov', 'XASAN XALILOV', 'individual', NULL, 'labzak'),
  ('LAZIZJON SODIQOV', 'LAZIZJON SODIQOV', 'individual', NULL, 'labzak'),
  ('jamshid aka', 'JAMSHID AKA', 'individual', NULL, 'labzak'),
  ('SAYIDAZIM MAHMUDOV', 'SAYIDAZIM MAHMUDOV', 'individual', NULL, 'labzak'),
  ('Yigitaliyev Alibek', 'YIGITALIYEV ALIBEK', 'individual', NULL, 'labzak'),
  ('MUROD ERKINBOEV', 'MUROD ERKINBOEV', 'individual', NULL, 'labzak'),
  ('Ravshan Ibragimov', 'RAVSHAN IBRAGIMOV', 'individual', NULL, 'labzak'),
  ('Doston Flex', 'DOSTON FLEX', 'individual', NULL, 'labzak'),
  ('SINOMA WIND POWER BLADE CENTRAL ASIA', 'SINOMA WIND POWER BLADE CENTRAL ASIA', 'company', NULL, 'labzak'),
  ('NOVUGEN PHARMA', 'NOVUGEN PHARMA', 'company', NULL, 'labzak'),
  ('LENOVO INT. COO. (иностранная компания)', 'LENOVO INT. COO. (ИНОСТРАННАЯ КОМПАНИЯ)', 'company', NULL, 'labzak'),
  ('SAIDAZIM MAHMUDOV', 'SAIDAZIM MAHMUDOV', 'company', NULL, 'labzak'),
  ('xalilov hasan', 'XALILOV HASAN', 'company', NULL, 'labzak'),
  ('Aliyev izzatbek', 'ALIYEV IZZATBEK', 'company', NULL, 'labzak'),
  ('Muminov jAXONBEK', 'MUMINOV JAXONBEK', 'company', NULL, 'labzak'),
  ('Samandar Nigmatullayev', 'SAMANDAR NIGMATULLAYEV', 'company', NULL, 'labzak'),
  ('Alibekov Yigitali', 'ALIBEKOV YIGITALI', 'company', NULL, 'labzak'),
  ('Amonjonov Ibodulloh', 'AMONJONOV IBODULLOH', 'company', NULL, 'labzak'),
  ('Muhammadazim olimov', 'MUHAMMADAZIM OLIMOV', 'company', NULL, 'labzak'),
  ('Xusayin muhammadjonov', 'XUSAYIN MUHAMMADJONOV', 'company', NULL, 'labzak'),
  ('KELAJAK PAYMENTS INNOVATIONS', 'KELAJAK PAYMENTS INNOVATIONS', 'company', NULL, 'labzak'),
  ('UFA BUILDGROUP', 'UFA BUILDGROUP', 'company', NULL, 'labzak'),
  ('Jenisov Agabek', 'JENISOV AGABEK', 'individual', NULL, 'labzak'),
  ('Farrux', 'FARRUX', 'individual', NULL, 'labzak'),
  ('Abdulqayumov Bahodir', 'ABDULQAYUMOV BAHODIR', 'individual', NULL, 'labzak'),
  ('Andrey', 'ANDREY', 'individual', NULL, 'labzak'),
  ('Ilyos', 'ILYOS', 'individual', NULL, 'labzak'),
  ('Nabiyev Nurimon', 'NABIYEV NURIMON', 'individual', NULL, 'labzak'),
  ('Alimova Husniyabonu', 'ALIMOVA HUSNIYABONU', 'individual', NULL, 'labzak'),
  ('INTELLIGENT IT DISTRIBUTION EAST', 'INTELLIGENT IT DISTRIBUTION EAST', 'company', NULL, 'labzak'),
  ('TGHAMYON', 'TGHAMYON', 'company', NULL, 'labzak'),
  ('ARSHIA HOME', 'ARSHIA HOME', 'company', NULL, 'labzak')
ON CONFLICT (name_normalized, branch_id) DO NOTHING;

-- ============================================
-- 6. LINK EXISTING TRANSACTIONS TO CLIENTS
-- ============================================
-- Update transactions to link to clients based on customer_name
UPDATE transactions t
SET client_id = c.id
FROM clients c
WHERE UPPER(t.customer_name) = c.name_normalized
  AND t.branch_id = c.branch_id
  AND t.client_id IS NULL;

-- ============================================
-- 7. SUMMARY
-- ============================================
DO $$
DECLARE
  client_count INT;
  linked_count INT;
BEGIN
  SELECT COUNT(*) INTO client_count FROM clients;
  SELECT COUNT(*) INTO linked_count FROM transactions WHERE client_id IS NOT NULL;
  RAISE NOTICE 'Clients created: %, Transactions linked: %', client_count, linked_count;
END $$;
